### PR TITLE
Byte array column

### PR DESCRIPTION
**Pull request by dionissqq**
GROK-10712

### CODE REVIEW

**Review by skalkin — CHANGES_REQUESTED** [review]
The animated gif is not that useful since it's not clear what is happening. I assume a file dialog shows up, but is not captured by the gif? Let's produce a better gif. Also, let's keep them 800x500 pixels

**Review by skalkin — COMMENTED** [review]
I meant the other way, w:800 and h:500. See examples: https://community.datagrok.ai/t/scatter-plot-updates/625

**Comment by dionissqq** [comment]
done

**Review by skalkin — APPROVED** [review]

**Comment by skalkin** [comment]
Thanks!

**Pull request merged**
