### PR TITLE
JS API: add default users IDs

### PR DESCRIPTION
**Pull request by AufarZakiev**

### CODE REVIEW

**Review by alex-aprm — APPROVED** [review]

**Comment by skalkin** [comment]
@alex-aprm @AufarZakiev Do we still need it?

**Comment by AufarZakiev** [comment]
No, @alex-aprm merged my PR recently. Will close it

**Comment by AufarZakiev** [comment]
Yes, we should merge it, I guess? Alex has approved it

**Comment by AufarZakiev** [comment]
@skalkin @alex-aprm May we merge it?

**Pull request merged**
